"use client";
/* eslint-disable @next/next/no-img-element */
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowUpRight, BarChart3, CalendarDays, CircleHelp, Layers3 } from "lucide-react";
import { ageLabel, displayNumber as n, getData, pollingInterval, shortAddress } from "@/lib/live-api";
import { EXPLORER, FEE_TIERS, TRACKED_SYMBOLS, type CorporateActions, type NetworkState, type PoolBook, type PriceBook, type StockAsset } from "@/lib/market-types";
import { ReferenceChart } from "./market-charts";
import { StockLogo } from "./stock-logo";
import { TradeTicket } from "./trade-ticket";
import type { WalletState } from "./wallet";
import "./market-terminal.css";

const compact = (value: string | number | null | undefined) => value != null && Number(value) > 0 ? new Intl.NumberFormat("en-US", { notation: "compact", maximumFractionDigits: 2 }).format(Number(value)) : "—";
const pretty = (value?: string | null) => value ? value.replaceAll("_", " ") : "Not reported";

export function MarketTerminal({ assets, book, network, symbol, onSelect, now, wallet, registryCached, priceError }: {
  assets: StockAsset[]; book?: PriceBook; network?: NetworkState; symbol: string; onSelect: (s: string) => void; now: number; wallet: WalletState; registryCached: boolean; priceError: string | null;
}) {
  const [allEvents, setAllEvents] = useState(false);
  const asset = assets.find((a) => a.symbol === symbol);
  const quote = book?.quotes.find((q) => q.symbol === symbol);
  const multiplier = asset ? Number(asset.multiplier) : null;
  const bid = quote && multiplier !== null ? Number(quote.bid) * multiplier : null, ask = quote && multiplier !== null ? Number(quote.ask) * multiplier : null;
  const spread = bid && ask ? (ask - bid) / ((ask + bid) / 2) * 10000 : null;
  const referenceOld = registryCached || !!book?.dataStatus || !!book?.cachedSymbols?.includes(symbol) || (!!quote && now - Date.parse(quote.generatedAt) > 90000);
  const pools = useQuery({ queryKey: ["pools", symbol], queryFn: ({ signal }) => getData<PoolBook>(`pools?symbol=${encodeURIComponent(symbol)}`, signal), enabled: !!asset, staleTime: 60000, refetchInterval: (q) => pollingInterval(90000, q.state.error, q.state.fetchFailureCount, q.state.data?.dataStatus?.retryAt) });
  const events = useQuery({ queryKey: ["corporate-actions"], queryFn: ({ signal }) => getData<CorporateActions>("corporate-actions", signal), staleTime: 3600000 });
  const displayedEvents = (events.data?.items ?? []).filter((e) => allEvents || e.symbol === symbol).slice(0, 6);
  const watch = TRACKED_SYMBOLS.map((s) => ({ asset: assets.find((a) => a.symbol === s), quote: book?.quotes.find((q) => q.symbol === s) }));
  const volumeMax = Math.max(1, ...watch.map(({ quote: q }) => Number(q?.dailyTradingVolume ?? 0)));
  return <div className="market-terminal">
    <div className="terminal-watchlist" aria-label="Tracked Stock Tokens">{watch.map(({ asset: a, quote: q }, i) => {
      const s = TRACKED_SYMBOLS[i], mid = a && q ? (Number(q.bid) + Number(q.ask)) / 2 * Number(a.multiplier) : null;
      const old = registryCached || !!book?.dataStatus || !!book?.cachedSymbols?.includes(s) || (!!q && now - Date.parse(q.generatedAt) > 90000);
      return <button key={s} className={s === symbol ? "active" : ""} aria-pressed={s === symbol} disabled={!a} onClick={() => onSelect(s)}><span><StockLogo symbol={s} size={26}/><b>{s}</b><i className={q?.halted ? "halted" : old ? "aged" : q ? "" : "waiting"}/></span><strong>{mid === null ? "—" : `$${n(mid)}`}</strong><small>{q?.halted ? "Underlying halted" : q ? `${old ? "Last · " : ""}${ageLabel(q.generatedAt, now)}` : "Reference pending"}</small></button>;
    })}</div>
    <div className="terminal-toolbar"><label><StockLogo symbol={symbol} size={30}/><select aria-label="Choose a Stock Token" value={symbol} onChange={(e) => onSelect(e.target.value)}>{assets.length ? assets.map((a) => <option key={a.address} value={a.symbol}>{a.symbol} — {a.name}</option>) : <option>{symbol}</option>}</select></label><span><i/>{assets.length || "—"} registered assets <b>·</b> {book?.quotes.length ?? 0} reference quotes</span></div>
    <div className="terminal-columns"><div className="terminal-analysis">
      <section className="asset-pulse"><div className="asset-pulse-heading"><div><span className="eyebrow stock-identity"><StockLogo symbol={symbol} size={38}/>{asset?.name ?? symbol} / STOCK TOKEN</span><h2>{bid !== null && ask !== null ? `$${n((bid + ask) / 2, 4)}` : "Loading reference"}</h2><p>USD reference per token <span className={referenceOld || quote?.halted ? "reference-aged" : ""}>{quote?.halted ? "Underlying halted" : referenceOld ? "Last source observation" : quote ? "Issuer quote" : "Awaiting issuer"}</span></p></div><img src="/artwork/execution.webp" alt=""/></div>
        <div className="pulse-metrics"><div><span>Reference bid</span><strong>{bid === null ? "—" : `$${n(bid, 4)}`}</strong></div><div><span>Reference ask</span><strong>{ask === null ? "—" : `$${n(ask, 4)}`}</strong></div><div><span>Bid / ask spread</span><strong>{spread === null ? "—" : n(spread, 2)}<small> bps</small></strong></div><div><span>Underlying volume</span><strong>{compact(quote?.dailyTradingVolume)}</strong></div></div>
        <div className="pulse-source"><span>Robinhood · {quote ? new Date(quote.generatedAt).toLocaleString() : "Source pending"}</span><span>Volume is the issuer’s daily underlying figure, not onchain volume.</span></div>
      </section>
      {(priceError || book?.unavailableSymbols?.length || registryCached) && <p className="terminal-alert" role="status"><CircleHelp size={16}/>{registryCached ? "Showing cached registry information. A fresh registry is required for trade preparation." : priceError ?? `Reference updates are pending for ${book?.unavailableSymbols?.join(", ")}. Other markets remain available.`}</p>}
      <ReferenceChart key={symbol} symbol={symbol} assets={assets} book={book} now={now} onSelect={onSelect} registryCached={registryCached} initialMode="spread"/>
      <section className="terminal-panel liquidity-board"><div className="terminal-section-heading"><div><span className="eyebrow">ONCHAIN LIQUIDITY</span><h3><Layers3 size={17}/> {symbol} / USDG venues</h3></div><span>{pools.data ? `${pools.data.pools.filter((p) => p.active).length} active${pools.data.failedReads ? " · incomplete reads" : " pools"}` : "Reading pools"}</span></div>
        <div className="liquidity-grid">{FEE_TIERS.map((fee) => { const pool = pools.data?.pools.find((p) => p.fee === fee); return <div key={fee} className={pool?.active ? "liquid" : ""}><span>{fee / 10000}% <small>fee tier</small></span><div className="venue-glyph" aria-hidden="true"><Layers3 size={30}/></div><strong>{pool?.active ? `${n(pool.priceUSDG, 4)}` : pools.data ? pool ? "Inactive" : pools.data.failedReads ? "Not verified" : "No pool" : "—"}</strong><small>{pool?.active ? "USDG / token · spot" : pools.error ? "Read failed" : pools.data ? pools.data.failedReads && !pool ? "Discovery read failed" : "No active route here" : "Checking this tier"}</small>{pool && <a href={`${EXPLORER}/address/${pool.address}`} target="_blank" rel="noreferrer">Pool contract<ArrowUpRight size={11}/></a>}</div>; })}</div>
        <p className="terminal-panel-note">{pools.error ? pools.error.message : pools.data?.dataStatus ? "Cached pool snapshot. Refreshing when the source recovers." : pools.data ? `Block ${pools.data.blockNumber} · ${ageLabel(pools.data.blockTimestamp, now)}.` : "Reading the official V3 factory."} Spot prices are not executable quotes. Use the trade ticket for your size.</p>
      </section>
    </div><aside className="terminal-trading">{asset ? <TradeTicket key={`${asset.address}-${wallet.demoWallet?.id ?? wallet.account ?? "guest"}-${wallet.chainId ?? "none"}`} asset={asset} now={now} wallet={wallet}/> : <div className="trade-ticket"><h3>Loading the official token registry…</h3><p>The trade ticket opens when token identity is verified.</p></div>}</aside></div>
    <div className="terminal-bottom"><section className="terminal-panel volume-board"><div className="terminal-section-heading"><div><span className="eyebrow">ACROSS YOUR WATCHLIST</span><h3><BarChart3 size={17}/> Underlying trading activity</h3></div></div><div className="volume-bars">{watch.map(({ asset: a, quote: q }, i) => <button key={TRACKED_SYMBOLS[i]} disabled={!a} onClick={() => onSelect(TRACKED_SYMBOLS[i])}><span className="stock-identity"><StockLogo symbol={TRACKED_SYMBOLS[i]} size={22}/>{TRACKED_SYMBOLS[i]}</span><div><i style={{ width: `${Math.max(0, Number(q?.dailyTradingVolume ?? 0) / volumeMax * 100)}%` }}/></div><strong>{compact(q?.dailyTradingVolume)}</strong></button>)}</div><p className="terminal-panel-note">Daily volume from each issuer quote. Bars use the same scale; source times can differ. A dash means volume was not supplied.</p></section>
      <section className="terminal-panel corporate-board"><div className="terminal-section-heading"><div><span className="eyebrow">FROM THE ISSUER</span><h3><CalendarDays size={17}/> Corporate actions</h3></div><button aria-pressed={allEvents} onClick={() => setAllEvents(!allEvents)}>{allEvents ? `Show ${symbol}` : "All assets"}</button></div><div className="event-timeline">{displayedEvents.length ? displayedEvents.map((event, i) => <div key={event.id ?? `${event.symbol}-${event.type}-${i}`}><span className="event-date" title={event.date ?? "Date not scheduled"}>{event.date ? <><b>{event.date.slice(8)}</b>{new Date(`${event.date}T12:00:00Z`).toLocaleString("en", { month: "short", timeZone: "UTC" })}<small>{event.date.slice(0,4)}</small></> : "TBD"}</span><div><span>{event.symbol} <small>{pretty(event.status)}</small></span><strong>{pretty(event.type)}</strong><p>{event.detail ?? "Details are unavailable in this view."}</p></div></div>) : <p className="terminal-empty">{events.isPending ? "Loading issuer events…" : events.error ? events.error.message : `No ${symbol} events were returned. View all assets to explore the issuer calendar.`}</p>}</div><p className="terminal-panel-note">Issuer processing dates, not dividend payment dates. {events.data?.dataStatus ? "Cached data · " : ""}{events.data ? `Fetched ${ageLabel(events.data.fetchedAt, now)}.` : ""}</p></section>
    </div>
    {asset && <section className="terminal-facts"><div><span>Token contract</span><a href={`${EXPLORER}/address/${asset.address}`} target="_blank" rel="noreferrer">{shortAddress(asset.address)}<ArrowUpRight size={12}/></a></div><div><span>Share-equivalent multiplier</span><strong>{n(asset.multiplier, 6)} / token</strong></div><div><span>Underlying overnight trading</span><strong>{pretty(asset.tradingCapabilities?.allDayTradability)}</strong></div><div><span>Network gas price · {network ? `${network.dataStatus || now - Date.parse(network.blockTimestamp) > 90000 ? "last · " : ""}${ageLabel(network.blockTimestamp, now)}` : "pending"}</span><strong>{network ? n(Number(network.gasPriceWei) / 1e9, 5) : "—"} gwei</strong></div>{asset.pendingMultiplier && <p>Scheduled token adjustment: {n(asset.pendingMultiplier, 6)} shares per token{asset.pendingMultiplierEffectiveTime ? ` · ${new Date(asset.pendingMultiplierEffectiveTime).toLocaleString()}` : ""}.</p>}<p>Stock Tokens provide issuer-defined financial exposure. Underlying trading capabilities do not determine whether an onchain swap can execute.</p></section>}
  </div>;
}
